name = OSU Main
description = Main layout set up for use with panels.
preview = preview.png
template = osumain-layout

; Regions
regions[header]         = Header
regions[navigation]     = Navigation bar
; regions[highlighted]    = Highlighted
; regions[help]           = Help
regions[content]        = Content
; regions[sidebar_first]  = First sidebar
; regions[sidebar_second] = Second sidebar
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/osumain/osumain.layout.css

; Settings
settings[toggle_logo] = 0
settings[default_logo] = 0